language: rust
rust:
  - nightly
sudo: required
os:
  - linux
  - osx
dist: trusty
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - xorg-dev
script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo build --verbose --features copypasta
  # Currently no tests
  # - cargo test --verbose
notifications:
  email: false
